default_platform(:ios)

platform :ios do
  lane :test do
    run_tests(
      project: "Palace.xcodeproj",
      devices: ["iPhone 12 Pro"],
      scheme: "Ekirjasto"
    )
  end
  lane :nodrm do
    build_app(
      project: "Palace.xcodeproj",
      scheme: "Ekirjasto",
      skip_package_ipa: true,
      skip_archive: true,
      skip_codesigning: true,
      silent: true
    )
  end
  lane :beta do |options|
    build_app(
      project: "Palace.xcodeproj",
      scheme: "Ekirjasto",
      include_symbols: true,
      include_bitcode: false,
      silent: true,
      output_name: options[:output_name],
      output_directory: options[:export_path],
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: { 
          "fi.kansalliskirjasto.e-kirjasto" => "Ad Hoc"
        }
      }
    )
  end
  lane :appstore do |options|
    build_app(
      project: "Palace.xcodeproj",
      scheme: "Ekirjasto",
      include_symbols: true,
      include_bitcode: false,
      export_options: {
        method: "app-store",
        provisioningProfiles: { 
          "fi.kansalliskirjasto.e-kirjasto" => "App Store"
        }
      }
    )
    pilot(
      api_key_path: "fastlane/fastlane.json",
      skip_submission: true,
      changelog: options[:changelog]
    )
  end
end
