name: Create Release Test
on: workflow_dispatch
jobs:
  create-release:
    runs-on: macOS-latest
    steps:
      - name: Force Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Checkout main repo and submodules
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
      - name: Checkout Certificates
        uses: actions/checkout@v2.3.4
        with:
          repository: ThePalaceProject/mobile-certificates
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
          path: ./mobile-certificates
      - name: Create release notes
        run: ./scripts/create-release-notes.sh
        env:
          BUILD_CONTEXT: ci
      - name: Verify path and version
        run: |
          echo "Path:    " $RELEASE_NOTES_PATH
          echo "Version: " $VERSION_NUM
        env:
          RELEASE_NOTES_PATH: ${{ env.RELEASE_NOTES_PATH }}
          VERSION_NUM: ${{ env.VERSION_NUM }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES_PATH: ${{ env.RELEASE_NOTES_PATH }}
          VERSION_NUM: ${{ env.VERSION_NUM }}
        with:
          tag_name: ${{ env.VERSION_NUM }}
          release_name: ${{ env.VERSION_NUM }}
          body_path: ${{ env.RELEASE_NOTES_PATH }}
          draft: true
