name: Unit Tests
on: workflow_dispatch
jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
      - name: Force Xcode 11.5
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app
      - name: Checkout main repo and submodules
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
      - name: Checkout Certificates
        uses: actions/checkout@v2.3.4
        with:
          repository: ThePalaceProject/mobile-certificates
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
          path: ./mobile-certificates
      - name: Checkout Adobe RMSDK
        uses: actions/checkout@v2.3.4
        with:
          repository: ThePalaceProject/mobile-drm-adeptconnector
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
          path: ./mobile-drm-adeptconnector
      - name: Uncompress Adobe RMSDK
        run: ./scripts/setup-repo-drm.sh
        env:
          BUILD_CONTEXT: ci
      - name: Build OpenSSL and curl
        run: ./scripts/build-openssl-curl.sh
        env:
          BUILD_CONTEXT: ci
      - name: Build non-Carthage 3rd party dependencies
        run: ./scripts/build-3rd-party-dependencies.sh
        env:
          BUILD_CONTEXT: ci
      - name: Carthage Bootstrap
        uses: devbotsxyz/carthage-bootstrap@v1
        with:
          github-token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
          platform: iOS
          cache: false
          verbose: true
      - name: Run Palace unit tests
        run: ./scripts/xcode-test.sh
        env:
          BUILD_CONTEXT: ci
