name: Palace Build
on: workflow_dispatch
jobs:
  upload-arc:
    runs-on: macOS-latest
    steps:
      - name: Force Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      - name: Checkout main repo and submodules
        uses: actions/checkout@v2.3.4
        with:
          submodules: true
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
      - name: Checkout Certificates
        uses: actions/checkout@v2.3.4
        with:
          repository: ThePalaceProject/mobile-certificates
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
          path: ./mobile-certificates
      - name: Checkout Adobe RMSDK
        uses: actions/checkout@v2.3.4
        with:
          repository: ThePalaceProject/mobile-drm-adeptconnector
          token: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}
          path: ./mobile-drm-adeptconnector
      - name: Uncompress Adobe RMSDK
        run: ./scripts/setup-repo-drm.sh
        env:
          BUILD_CONTEXT: ci
      - name: Build non-Carthage 3rd party dependencies
        run: ./scripts/build-3rd-party-dependencies.sh
        env:
          BUILD_CONTEXT: ci
      - name: Install provisioning profile
        run: ./scripts/install-profile.sh
        env:
          BUILD_CONTEXT: ci
          CI_APPSTORE_MP_BASE64: ${{ secrets.CI_APPSTORE_MP_BASE64 }}
          CI_DISTRIBUTION_CERT_BASE64: ${{ secrets.CI_DISTRIBUTION_CERT_BASE64 }}
          CI_DISTRIBUTION_CERT_PW: ${{ secrets.CI_DISTRIBUTION_CERT_PW }}
          CI_KEYCHAIN_PW: ${{ secrets.CI_KEYCHAIN_PW }}
      - name: Export for App Store
        run: ./scripts/xcode-export-appstore.sh simplye
        env:
          BUILD_CONTEXT: ci
